base:
  NUMBER_OF_PROCESSES: 2

agent:
  -  id: bj_lvs212
     ipadd: 10.13.80.212
     cluster: bj_lvs_cluster
     area: bj
     port: 60090

  -  id: bj_lvs213
     ipadd: 10.13.80.213
     cluster: bj_lvs_cluster
     area: bj
     port: 60090


cluster:
  - id: bj_lvs_cluster
    area: 北京
    descript: 北京LVS集群
    agent: ['bj_lvs212','bj_lvs213']
    admin_mail_group: ['liujun5@staff.weibo.com']
    manager_user: []